# Problem Statement

1. 🛠️ The overall problem is to develop a text classification system using a pre-trained DistilBert model that can accurately predict categories based on textual input.

2. 📝 The input feature, denoted as 'X', consists of raw text strings sourced from a dataset, which the model processes to predict categorical labels.

3. 🎯 The target variable, referred to as 'label', represents the actual categories of the text, which are used to train the model and evaluate its accuracy.

4. 📊 The model's performance is assessed through metrics such as the confusion matrix and accuracy, comparing the predicted labels against the actual labels.

5. 🔧 The project involves not only fine-tuning a pre-trained language model on a specific dataset but also validating its effectiveness on both a smaller sample and a larger subset to ensure robustness and scalability of the predictions.

#Install the necessary libraries



1. **Install Accelerate**:
2. **Install Transformers and Datasets**:
3. **Upgrade PyArrow**:

Import Libraries

1. **Import Standard Data Science Libraries**:
3. **Import PyTorch and Transformers for NLP**:

In [1]:
## Write your code here
!pip install accelerate
!pip install transformers[torch]
!pip install datasets
!pip install evaluate
!pip install --upgrade pyarrow

Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (26.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (1.8.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.5.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (0.1.2)
Requirement already satisfied: transformers[torch] in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (3.25.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (1.8.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (4.67.3)
Requirement already satisfied: torch>=2.2 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (2.10.0+cu128)
Requirement already satisfied: accelerate>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from transformers[torch]) (1.13.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.1.0->transformers[torch]) (5.9.5)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers[torch]) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers[torch]) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers[torch]) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers[torch]) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers[torch]) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->transformers[torch]) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.2->transformers[torch]) (1.5.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.2->transformers[torch]) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.2->transformers[torch]) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (0.1.2)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.25.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.8.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)

# Import Emotions Data. Target variable is 'Label'

Import the data from https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Final_Emotion_Data/five_emotions_data.csv

Display the first few rows of the dataset to understand its structure

In [3]:
## Write your code here
!wget https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Final_Emotion_Data/five_emotions_data.csv

--2026-04-08 01:28:23--  https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Final_Emotion_Data/five_emotions_data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4092906 (3.9M) [text/plain]
Saving to: ‘five_emotions_data.csv.1’

five_emotions_data. 100%[===================>]   3.90M  --.-KB/s    in 0.04s

2026-04-08 01:28:24 (90.6 MB/s) - ‘five_emotions_data.csv.1’ saved [4092906/4092906]

In [14]:
import pandas as pd
emotion_df = pd.read_csv('five_emotions_data.csv')
emotion_df.head()

   Id    Emotion                                               Text  label
0   1    sadness                            i didnt feel humiliated      3
1   2    sadness  i can go from feeling so hopeless to so damned...      3
2   4       love  i am ever feeling nostalgic about the fireplac...      1
3   6    sadness  ive been feeling a little burdened lately wasn...      3
4   9  happiness  i have been with petronas for years i feel tha...      0

In [15]:
emotion_df['Emotion'].value_counts()

Emotion
happiness    10571
sadness       9831
neutral       8638
worry         8459
love          5146
Name: count, dtype: int64

# Use distilbert model without finetunung

Here are concise instructions to write and execute the Python code you provided, which utilizes a pre-trained DistilBERT model from the `transformers` library for text classification without fine-tuning:

Step 1: Install and Import Libraries
1. **Install the necessary Python packages** if they're not already installed:

2. **Import the libraries** in your Python script:


 Step 2: Set Up the DistilBERT Model
1. **Initialize the DistilBERT pipeline** for text classification. Ensure you have GPU support (CUDA) if available:


 Step 3: Prepare and Predict with Your Dataset
1. **Sample and preprocess the dataset**:
   - Assuming `emotions_data` is already loaded:

2. **Classify text** using the model and extract predictions:


Step 4: Evaluate Model Performance
1. **Calculate and print the confusion matrix** and accuracy:

In [22]:
## Write your code here
from transformers import pipeline
from sklearn.metrics import confusion_matrix, accuracy_score
classifier = pipeline("text-classification", model="distilbert-base-uncased")
#

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [19]:
#pass the data in to model one by one on sample data
sample_data= emotion_df.sample(n=1000, random_state=42)

#CONSIDER FIRST 100 CHARCTERS
sample_data['Text'] = sample_data['Text'].apply(lambda x: " ".join(x.split())[ :100])

In [23]:
sample_data["berrt_predicted"]= sample_data['Text'].apply(lambda x: classifier(x)[0]['label'])

In [24]:
sample_data

,Id,Emotion,Text,label,berrt_predicted
1900,2690,sadness,i social and dreaming about things that make y...,3,LABEL_1
20627,27544,worry,"is missing training tonight, the lurgy is on m...",4,LABEL_0
12481,17415,worry,my HD is full. need to cleanup a lot,4,LABEL_0
30267,39810,sadness,"i'm watching missing pieces, just coz the them...",3,LABEL_0
14420,19838,sadness,rain got so big weather so cold right now,3,LABEL_0
...,...,...,...,...,...
7294,10282,happiness,i feel like number is the most important going...,0,LABEL_1
19854,26614,worry,Great. I let my friend use my ipod this mornin...,4,LABEL_0
24494,32441,neutral,@nkotb how come u all don't seem to excited to...,2,LABEL_0
36962,48616,happiness,http://twitpic.com/4wgoi - At bus boys and poe...,0,LABEL_0
38711,50901,neutral,@MCRsavedMilife night,2,LABEL_0

In [28]:
sample_data["ber_predicted_number"]= sample_data["berrt_predicted"].apply(lambda x : x[-1])
#convert as int
sample_data["ber_predicted_number"]= sample_data["ber_predicted_number"].astype(int)
sample_data.head()

,Id,Emotion,Text,label,berrt_predicted,ber_predicted_number
1900,2690,sadness,i social and dreaming about things that make y...,3,LABEL_1,1
20627,27544,worry,"is missing training tonight, the lurgy is on m...",4,LABEL_0,0
12481,17415,worry,my HD is full. need to cleanup a lot,4,LABEL_0,0
30267,39810,sadness,"i'm watching missing pieces, just coz the them...",3,LABEL_0,0
14420,19838,sadness,rain got so big weather so cold right now,3,LABEL_0,0

In [32]:
# create confusion matrix
cm = confusion_matrix(sample_data['label'], sample_data['ber_predicted_number'])
print(cm)
# calculate teh accuracy
accuracy = accuracy_score(sample_data['label'], sample_data['ber_predicted_number'])
print(accuracy)

[[203  49   0   0   0]
 [102  14   0   0   0]
 [184  20   0   0   0]
 [182  43   0   0   0]
 [169  34   0   0   0]]
0.217

# Finetuning the model with our data

1. Begin by importing necessary libraries including `DistilBertTokenizer` and `DistilBertForSequenceClassification` from `transformers`, `load_dataset`, `DatasetDict`, `ClassLabel`, and `Dataset` from `datasets`, `pandas`, `train_test_split` from `sklearn.model_selection`, and `torch`.

2. Load your sample data into a pandas DataFrame, `sample_data`.

3. Convert the DataFrame into a `Dataset` object using `Dataset.from_pandas()` method.

4. Split the data into training and testing sets using the `train_test_split` method from the `datasets` library, setting aside 20% of the data for testing.

5. Create a `DatasetDict` to organize the datasets into 'train' and 'test' subsets.

6. Load the `DistilBertTokenizer` from the `transformers` library using the pretrained 'distilbert-base-uncased' model.

7. Set the tokenizer's padding token to the end-of-sequence token and update the padding token ID accordingly. Add a special padding token '[PAD]' to the tokenizer.

8. Define a function, `tokenize_function`, that tokenizes the texts in the dataset. Ensure the texts are padded to a maximum length of 100 characters and truncated if necessary.

9. Apply the `tokenize_function` to the datasets using the `.map()` method with `batched=True` to process batches of texts at once.

In [34]:
#Write your code here
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification
from transformers import TrainingArguments, Trainer
from datasets import load_dataset, DatasetDict, ClassLabel, Dataset
from sklearn.model_selection import train_test_split
import pandas as pd
import torch

In [35]:
sample_HF = Dataset.from_pandas(sample_data)
sample_HF

Dataset({
    features: ['Id', 'Emotion', 'Text', 'label', 'berrt_predicted', 'ber_predicted_number', '__index_level_0__'],
    num_rows: 1000
})

In [37]:
train_test_split= sample_HF.train_test_split(test_size=0.2)
train_test_split
dataset= DatasetDict({
    'train': train_test_split['train'],
    'test': train_test_split['test']
})
dataset

DatasetDict({
    train: Dataset({
        features: ['Id', 'Emotion', 'Text', 'label', 'berrt_predicted', 'ber_predicted_number', '__index_level_0__'],
        num_rows: 800
    })
    test: Dataset({
        features: ['Id', 'Emotion', 'Text', 'label', 'berrt_predicted', 'ber_predicted_number', '__index_level_0__'],
        num_rows: 200
    })
})

In [38]:
tokenzier= DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
# padding
tokenzier.pad_token= '[PAD]'
tokenzier.pad_token_id= tokenzier.encode(tokenzier.pad_token)[0]

In [39]:
# make tokenize function
def tokenize_function(examples):
    return tokenzier(examples["Text"], padding="max_length", max_length=100, truncation=True)

In [43]:
# Training arguments
training_args = TrainingArguments(output_dir='./results',
                                  num_train_epochs=5,
                                  logging_dir='./logs',
                                  )
model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=5)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset['train'].map(tokenize_function, batched=True),
    eval_dataset=dataset['test'].map(tokenize_function, batched=True),
)

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/800 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

In [44]:
#save the model
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [47]:
model.save_pretrained("./distilbert_my_finetuned")
tokenzier.save_pretrained("./distilbert_my_finetuned")
trainer.save_model("my_1st_finedtuned")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

## Load and Train the model

1. Load the `DistilBertForSequenceClassification` model from the `transformers` library, using the pretrained 'distilbert-base-uncased' model. Specify `num_labels` based on your classification needs and set `pad_token_id` to the tokenizer's end-of-sequence token ID.

2. Set up the training configuration using `TrainingArguments`. Define an `output_dir` for storing training results, set `num_train_epochs` for the number of training epochs, specify a `logging_dir` for training logs, and choose `evaluation_strategy` as 'epoch' to perform evaluations at the end of each epoch.

3. Initialize a `Trainer` object with the model, training arguments, and datasets for training and evaluation. Specify the training dataset using `tokenized_datasets['train']` and the evaluation dataset as `tokenized_datasets['test']`.

4. Begin the training process by invoking the `train()` method on the `Trainer`.

5. Specify a directory where you want to save both the trained model and the tokenizer, e.g., "./distilbert_finetuned".

6. Save the trained model and tokenizer to the specified directory using the `save_pretrained()` method for both the model and tokenizer.

7. Additionally, save the model to another directory or under another name using the `save_model()` method of the `Trainer`.

8. Compress the model directory into a ZIP file using a zip utility, specifying the target directory and the name for the ZIP file, e.g., "distilbert_finetuned_10k.zip".

## Make Predictions

1. Define a function, `make_prediction`, which takes a single text string as input. Inside this function:
   - Tokenize the text using your pretrained tokenizer. Specify that tensors should be returned as PyTorch tensors (`return_tensors="pt"`).
   - Send the tokenized inputs to a CUDA device for GPU acceleration.
   - Pass the inputs to your pretrained model and obtain the outputs.
   - Extract the logits from the outputs and determine the predicted class by finding the index of the maximum logit value.
   - Convert the prediction tensor from GPU to CPU and transform it into a numpy array.
   - Return the prediction.

2. Apply the `make_prediction` function to the "Text" column of your `sample_data` DataFrame, extracting the first element of the returned array to a new column named `finetuned_predicted`.

3. Calculate the confusion matrix using `confusion_matrix` from `sklearn.metrics`, comparing the actual labels and the predicted labels from your DataFrame. Print the resulting confusion matrix.

4. Compute and print the accuracy of your predictions by dividing the sum of the diagonal elements of the confusion matrix by the total number of predictions.

5. Select a large subset (e.g., 40,000 samples) from another dataset (assumed to be `emotions_data` here), using a fixed random state for reproducibility.

6. Apply the `make_prediction` function to the "Text" column of this large dataset, storing the results in a new column named `finetuned_predicted`.

7. Calculate and print the confusion matrix for this larger dataset to compare the predicted labels against the actual labels.

8. Compute and print the accuracy for this dataset in the same manner as described above.

In [50]:
# make the function for prediction
def make_prediction(text):
    inputs = tokenzier(text, return_tensors="pt", padding=True, truncation=True)
    inputs= inputs.to('cuda')
    outputs = model(**inputs)
    predict = outputs.logits.argmax(-1)
    prediction = predict.cpu().detach().numpy()
    return prediction

In [54]:
sample_data['finetuned_predicted'] = sample_data['Text'].apply(lambda x: make_prediction(str(x))[0])
sample_data

,Id,Emotion,Text,label,berrt_predicted,ber_predicted_number,finetuned_predicted
1900,2690,sadness,i social and dreaming about things that make y...,3,LABEL_1,1,3
20627,27544,worry,"is missing training tonight, the lurgy is on m...",4,LABEL_0,0,4
12481,17415,worry,my HD is full. need to cleanup a lot,4,LABEL_0,0,4
30267,39810,sadness,"i'm watching missing pieces, just coz the them...",3,LABEL_0,0,3
14420,19838,sadness,rain got so big weather so cold right now,3,LABEL_0,0,4
...,...,...,...,...,...,...,...
7294,10282,happiness,i feel like number is the most important going...,0,LABEL_1,1,0
19854,26614,worry,Great. I let my friend use my ipod this mornin...,4,LABEL_0,0,4
24494,32441,neutral,@nkotb how come u all don't seem to excited to...,2,LABEL_0,0,2
36962,48616,happiness,http://twitpic.com/4wgoi - At bus boys and poe...,0,LABEL_0,0,0
38711,50901,neutral,@MCRsavedMilife night,2,LABEL_0,0,2

In [55]:
# make confusion matrix
cm = confusion_matrix(sample_data['label'], sample_data['finetuned_predicted'])
print(cm)
# accuracy
accuracy = accuracy_score(sample_data['label'], sample_data['finetuned_predicted'])
print(accuracy)

[[225  12   7   6   2]
 [ 24  86   3   1   2]
 [  6   5 173   3  17]
 [  5   4   2 201  13]
 [  5   2  13   6 177]]
0.862